// Generated by wrangler types — OZ Policy Builder
declare namespace Cloudflare {
	interface Env {
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
		NODE_ENV: string;
	}
}
interface Env extends Cloudflare.Env {}
