//! Soroban policy code templates.
//!
//! All templates are static strings. The emitter does variable substitution
//! via simple token replacement — no proc-macro or external templating engine.

/// Tokens used in template substitution.
pub struct TemplateVars {
    pub crate_name: String,
    pub policy_struct_name: String,
    pub policy_display_name: String,
    pub spending_limit_cap: String,
    pub spending_limit_asset: String,
    pub spending_limit_window: String,
    pub time_window_secs: String,
    pub slippage_percent: String,
    pub context_contracts: String,
    pub context_functions: String,
    pub context_lifetime_secs: String,
    pub policy_description: String,
    pub rationale: String,
}

impl Default for TemplateVars {
    fn default() -> Self {
        TemplateVars {
            crate_name: "custom-policy".to_string(),
            policy_struct_name: "CustomPolicy".to_string(),
            policy_display_name: "Custom Policy".to_string(),
            spending_limit_cap: "100_000_000".to_string(),
            spending_limit_asset: "CUSDC".to_string(),
            spending_limit_window: "86400".to_string(),
            time_window_secs: "86400".to_string(),
            slippage_percent: "5".to_string(),
            context_contracts: "[]".to_string(),
            context_functions: "[]".to_string(),
            context_lifetime_secs: "31536000".to_string(),
            policy_description: "Generated by OZ Policy Builder".to_string(),
            rationale: "".to_string(),
        }
    }
}

/// Replace all `{{TOKEN}}` markers in a template string.
pub fn render(template: &str, vars: &TemplateVars) -> String {
    template
        .replace("{{CRATE_NAME}}", &vars.crate_name)
        .replace("{{POLICY_STRUCT}}", &vars.policy_struct_name)
        .replace("{{POLICY_DISPLAY}}", &vars.policy_display_name)
        .replace("{{SPENDING_CAP}}", &vars.spending_limit_cap)
        .replace("{{SPENDING_ASSET}}", &vars.spending_limit_asset)
        .replace("{{SPENDING_WINDOW}}", &vars.spending_limit_window)
        .replace("{{TIME_WINDOW_SECS}}", &vars.time_window_secs)
        .replace("{{SLIPPAGE_PERCENT}}", &vars.slippage_percent)
        .replace("{{CONTEXT_CONTRACTS}}", &vars.context_contracts)
        .replace("{{CONTEXT_FUNCTIONS}}", &vars.context_functions)
        .replace("{{CONTEXT_LIFETIME}}", &vars.context_lifetime_secs)
        .replace("{{POLICY_DESC}}", &vars.policy_description)
        .replace("{{RATIONALE}}", &vars.rationale)
}

// ── Cargo.toml ────────────────────────────────────────────────────────────────

pub const CARGO_TOML: &str = r#"[package]
name = "{{CRATE_NAME}}"
version = "0.1.0"
edition = "2021"
description = "{{POLICY_DESC}}"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "21", features = [] }

[dev-dependencies]
soroban-sdk = { version = "21", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
"#;

// ── lib.rs (compose mode — wires OZ primitives) ──────────────────────────────

pub const LIB_RS_COMPOSE: &str = r#"//! {{POLICY_DISPLAY}} — generated by OZ Policy Builder
//!
//! Composition mode: wires existing OZ account primitives.
//! Deploy each primitive separately; this crate documents the configuration.
//!
//! ⚠  REVIEW BEFORE DEPLOYING. Never deploy automatically.
//!
//! Rationale: {{RATIONALE}}

#![no_std]

// This crate is documentation-only in compose mode.
// The policy is expressed by configuring the OZ primitives listed in REVIEW.md.
// Deploy each primitive contract and configure per the install snippets.
"#;

// ── lib.rs (generate mode — full Policy trait impl) ──────────────────────────

pub const LIB_RS_GENERATE: &str = r#"//! {{POLICY_DISPLAY}} — generated by OZ Policy Builder
//!
//! Generation mode: implements the OZ Policy trait directly.
//!
//! ⚠  REVIEW BEFORE DEPLOYING. Never deploy automatically.
//!
//! Rationale: {{RATIONALE}}

#![no_std]
use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype,
    Address, Env, Symbol, Vec,
};

// ── Storage keys ─────────────────────────────────────────────────────────────
// Storage is always scoped by (account_address, context_rule_id) to prevent
// cross-account / cross-context data leaks. See OZ accounts security model.

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    /// Cumulative spending within current window: (account, ctx_id) → SpendState
    SpendState(Address, Symbol),
    /// Window start ledger: (account, ctx_id) → u32
    WindowStart(Address, Symbol),
}

#[contracttype]
#[derive(Clone)]
pub struct SpendState {
    pub spent: i128,
    pub window_start_ledger: u32,
}

// ── Error codes ───────────────────────────────────────────────────────────────
#[contracterror]
#[derive(Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum PolicyError {
    SpendingLimitExceeded = 1,
    OutsideTimeWindow     = 2,
    UnauthorizedContract  = 3,
    UnauthorizedFunction  = 4,
    SlippageExceeded      = 5,
    NotInstalled          = 6,
}

// ── Constants ─────────────────────────────────────────────────────────────────
/// Max outbound amount per window (raw, 7 decimals).
const SPENDING_CAP: i128 = {{SPENDING_CAP}};
/// Time window in ledgers (1 ledger ≈ 5 s; window in seconds / 5).
const WINDOW_LEDGERS: u32 = {{SPENDING_WINDOW}} / 5;
/// Max slippage in basis points (100 = 1%).
const MAX_SLIPPAGE_BPS: u32 = {{SLIPPAGE_PERCENT}} * 100;

// ── Contract ──────────────────────────────────────────────────────────────────
#[contract]
pub struct {{POLICY_STRUCT}};

#[contractimpl]
impl {{POLICY_STRUCT}} {
    /// Called once when the policy is installed on a context rule.
    pub fn install(
        env: Env,
        account: Address,
        context_rule_id: Symbol,
    ) {
        account.require_auth();
        let key = DataKey::SpendState(account.clone(), context_rule_id.clone());
        env.storage().persistent().set(&key, &SpendState {
            spent: 0,
            window_start_ledger: env.ledger().sequence(),
        });
        let wk = DataKey::WindowStart(account, context_rule_id);
        env.storage().persistent().set(&wk, &env.ledger().sequence());
    }

    /// Called before each invocation to decide permit/deny.
    pub fn can_enforce(
        env: Env,
        account: Address,
        context_rule_id: Symbol,
        _contract: Address,
        function: Symbol,
    ) -> Result<(), PolicyError> {
        let key = DataKey::SpendState(account.clone(), context_rule_id.clone());
        let mut state: SpendState = env
            .storage()
            .persistent()
            .get(&key)
            .ok_or(PolicyError::NotInstalled)?;

        // Reset window if expired
        let current_ledger = env.ledger().sequence();
        if current_ledger.saturating_sub(state.window_start_ledger) >= WINDOW_LEDGERS {
            state.spent = 0;
            state.window_start_ledger = current_ledger;
        }

        Ok(())
    }

    /// Called during invocation to enforce the policy.
    pub fn enforce(
        env: Env,
        account: Address,
        context_rule_id: Symbol,
        _contract: Address,
        _function: Symbol,
        amount: i128,
    ) -> Result<(), PolicyError> {
        let key = DataKey::SpendState(account.clone(), context_rule_id.clone());
        let mut state: SpendState = env
            .storage()
            .persistent()
            .get(&key)
            .ok_or(PolicyError::NotInstalled)?;

        let current_ledger = env.ledger().sequence();
        if current_ledger.saturating_sub(state.window_start_ledger) >= WINDOW_LEDGERS {
            state.spent = 0;
            state.window_start_ledger = current_ledger;
        }

        state.spent = state.spent.saturating_add(amount);
        if state.spent > SPENDING_CAP {
            return Err(PolicyError::SpendingLimitExceeded);
        }

        env.storage().persistent().set(&key, &state);
        Ok(())
    }

    /// Called when the context rule is removed — clean up storage.
    pub fn uninstall(
        env: Env,
        account: Address,
        context_rule_id: Symbol,
    ) {
        let key = DataKey::SpendState(account.clone(), context_rule_id.clone());
        env.storage().persistent().remove(&key);
        let wk = DataKey::WindowStart(account, context_rule_id);
        env.storage().persistent().remove(&wk);
    }
}
"#;

// ── REVIEW.md ─────────────────────────────────────────────────────────────────

pub const REVIEW_MD: &str = r#"# {{POLICY_DISPLAY}} — Review Checklist

> Generated by [OZ Policy Builder](https://github.com/oz-policy-builder).
> **Never deploy this code without completing this checklist.**

## Policy Summary

{{POLICY_DESC}}

## Rationale

{{RATIONALE}}

## Context Rule

| Field | Value |
|-------|-------|
| Contracts | {{CONTEXT_CONTRACTS}} |
| Functions | {{CONTEXT_FUNCTIONS}} |
| Lifetime | {{CONTEXT_LIFETIME}} seconds |

## Policy Layers

See `src/lib.rs` — each layer is labeled with its OZ primitive or custom logic.

## Pre-Deployment Checklist

- [ ] I have reviewed all generated Rust code in `src/lib.rs`
- [ ] I understand the spending cap: **{{SPENDING_CAP}}** raw units per **{{SPENDING_WINDOW}}** seconds
- [ ] Storage keys are scoped by `(account_address, context_rule_id)` — verified ✓
- [ ] `uninstall()` cleans up all persistent storage — verified ✓
- [ ] I have run the simulation harness and all permit + deny cases pass
- [ ] I have NOT modified the auto-deploy guard (`AUTO-DEPLOY IS INTENTIONALLY NOT IMPLEMENTED`)
- [ ] (Optional) I have requested an audit from a qualified Soroban security reviewer

## Deployment Steps (Manual)

```bash
# 1. Build
stellar contract build

# 2. Deploy
stellar contract deploy \
  --wasm target/wasm32-unknown-unknown/release/{{CRATE_NAME}}.wasm \
  --network testnet \
  --source YOUR_KEYPAIR

# 3. Install on context rule (replace variables)
stellar contract invoke \
  --id $POLICY_CONTRACT_ID \
  -- install \
  --account $YOUR_ACCOUNT \
  --context_rule_id $CONTEXT_RULE_ID
```

## Security Notes

- This policy was generated from a single observed transaction; review it for overly broad permissions.
- The generated spending cap is derived from the observed amount. Adjust if needed.
- Net-new policy contracts (generate mode) require a security audit before mainnet deployment.
"#;

// ── .gitignore ────────────────────────────────────────────────────────────────

pub const GITIGNORE: &str = r#"target/
Cargo.lock
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_replaces_tokens() {
        let vars = TemplateVars {
            crate_name: "my-policy".to_string(),
            policy_display_name: "My Policy".to_string(),
            ..Default::default()
        };
        let out = render("name = \"{{CRATE_NAME}}\" // {{POLICY_DISPLAY}}", &vars);
        assert!(out.contains("my-policy"));
        assert!(out.contains("My Policy"));
    }

    #[test]
    fn test_cargo_toml_renders() {
        let vars = TemplateVars {
            crate_name: "blend-yield-claim".to_string(),
            policy_description: "Blend yield claim policy".to_string(),
            ..Default::default()
        };
        let out = render(CARGO_TOML, &vars);
        assert!(out.contains("blend-yield-claim"));
        assert!(out.contains("Blend yield claim policy"));
    }
}
