//! Blend yield claim policy — reference example generated by OZ Policy Builder.
//!
//! ⚠  REVIEW BEFORE DEPLOYING. Never deploy automatically.
//!
//! This policy allows a delegated agent to claim yield from a Blend pool
//! with a spending cap of 100 USDC per week.

#![no_std]
use soroban_sdk::{contract, contracterror, contractimpl, contracttype, Address, Env, Symbol};

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    SpendState(Address, Symbol),
}

#[contracttype]
#[derive(Clone)]
pub struct SpendState {
    pub spent: i128,
    pub window_start_ledger: u32,
}

#[contracterror]
#[derive(Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum PolicyError {
    SpendingLimitExceeded = 1,
    NotInstalled = 2,
}

/// 100 USDC (7 decimals) per week
const SPENDING_CAP: i128 = 1_000_000_000;
/// 1 week in ledgers (604800 s / 5 s per ledger)
const WINDOW_LEDGERS: u32 = 120_960;

#[contract]
pub struct BlendYieldClaimPolicy;

#[contractimpl]
impl BlendYieldClaimPolicy {
    pub fn install(env: Env, account: Address, context_rule_id: Symbol) {
        account.require_auth();
        env.storage().persistent().set(
            &DataKey::SpendState(account, context_rule_id),
            &SpendState { spent: 0, window_start_ledger: env.ledger().sequence() },
        );
    }

    pub fn can_enforce(
        env: Env,
        account: Address,
        context_rule_id: Symbol,
        _contract: Address,
        _function: Symbol,
    ) -> Result<(), PolicyError> {
        env.storage()
            .persistent()
            .get::<_, SpendState>(&DataKey::SpendState(account, context_rule_id))
            .map(|_| ())
            .ok_or(PolicyError::NotInstalled)
    }

    pub fn enforce(
        env: Env,
        account: Address,
        context_rule_id: Symbol,
        _contract: Address,
        _function: Symbol,
        amount: i128,
    ) -> Result<(), PolicyError> {
        let key = DataKey::SpendState(account.clone(), context_rule_id);
        let mut state: SpendState = env
            .storage()
            .persistent()
            .get(&key)
            .ok_or(PolicyError::NotInstalled)?;

        let cur = env.ledger().sequence();
        if cur.saturating_sub(state.window_start_ledger) >= WINDOW_LEDGERS {
            state.spent = 0;
            state.window_start_ledger = cur;
        }

        state.spent = state.spent.saturating_add(amount);
        if state.spent > SPENDING_CAP {
            return Err(PolicyError::SpendingLimitExceeded);
        }
        env.storage().persistent().set(&key, &state);
        Ok(())
    }

    pub fn uninstall(env: Env, account: Address, context_rule_id: Symbol) {
        env.storage()
            .persistent()
            .remove(&DataKey::SpendState(account, context_rule_id));
    }
}
